name: CI

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
    - uses: azure/appservice-actions/webapp@master
    - name: Deploy to app service
      with:
        app-name: electronics-cchoi34
        publish-profile: ${{ secrets.publishProfile }}
        package: '.'
